<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\Process\Process;

class DatabaseBackupService
{
    /**
     * Create a database backup.
     *
     * @return array ['success' => bool, 'message' => string, 'filename' => string|null, 'size' => string|null]
     */
    public function createBackup()
    {
        try {
            $dbName = config('database.connections.mysql.database');
            $dbUser = config('database.connections.mysql.username');
            $dbPass = config('database.connections.mysql.password');
            $dbHost = config('database.connections.mysql.host');
            $dbPort = config('database.connections.mysql.port');

            $filename = $dbName . '_' . date('Y-m-d_His') . '.sql';
            $backupPath = $this->backupPath($filename);
            $backupDisk = Storage::disk('s3');

            $dumpOutput = null;

            try {
                // Prefer native dump tools when available.
                $mysqldumpPath = $this->findMysqldump();
                $command = [
                    $mysqldumpPath,
                    '--host=' . $dbHost,
                    '--port=' . $dbPort,
                    '--user=' . $dbUser,
                    '--single-transaction',
                    '--routines',
                    '--triggers',
                    $dbName,
                ];

                // Inherit full OS environment and append MYSQL_PWD.
                // On Windows, dropping core env vars can break TCP initialization in mysqldump.
                $env = getenv();
                if (!is_array($env)) {
                    $env = [];
                }
                if (!empty($dbPass)) {
                    $env['MYSQL_PWD'] = $dbPass;
                }

                $process = new Process($command, null, $env);
                $process->setTimeout(300);
                $process->run();

                if (!$process->isSuccessful()) {
                    return [
                        'success' => false,
                        'message' => 'Backup failed. Error: ' . $this->formatProcessError(
                            $process,
                            'The database dump command failed.'
                        )
                    ];
                }

                $dumpOutput = $process->getOutput();
            } catch (\RuntimeException $e) {
                // Railway/containers may not ship mysqldump. Fall back to a PHP-generated SQL dump.
                $dumpOutput = $this->buildSqlDumpWithPdo($dbName);
            }

            if (trim($dumpOutput) === '') {
                return [
                    'success' => false,
                    'message' => 'Backup failed. The dump command returned an empty result.'
                ];
            }

            $stored = $backupDisk->put($backupPath, $dumpOutput, [
                'ContentType' => 'application/sql',
            ]);

            if (!$stored || !$backupDisk->exists($backupPath)) {
                return [
                    'success' => false,
                    'message' => 'Backup failed. Unable to upload SQL file to cloud storage.'
                ];
            }

            $fileSize = (int) $backupDisk->size($backupPath);

            if ($fileSize <= 0) {
                $backupDisk->delete($backupPath);
                return [
                    'success' => false,
                    'message' => 'Backup failed. Output file is empty.'
                ];
            }

            return [
                'success' => true,
                'message' => "Backup created successfully: {$filename}",
                'filename' => $filename,
                'size' => $this->formatBytes($fileSize)
            ];

        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => 'Backup failed: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Build a backup object key within the configured backup folder.
     */
    private function backupPath(string $filename): string
    {
        $prefix = trim((string) config('filesystems.backup_prefix', 'backups'), '/');
        $safeFilename = basename($filename);

        return $prefix === '' ? $safeFilename : $prefix . '/' . $safeFilename;
    }

    /**
     * Build a SQL dump without external binaries using PDO and MySQL metadata.
     */
    private function buildSqlDumpWithPdo(string $dbName): string
    {
        $connection = DB::connection('mysql');
        $pdo = $connection->getPdo();

        $dump = [];
        $dump[] = '-- SQL dump generated by application fallback';
        $dump[] = '-- Database: ' . $dbName;
        $dump[] = '-- Generated at: ' . now()->toDateTimeString();
        $dump[] = 'SET FOREIGN_KEY_CHECKS=0;';
        $dump[] = '';

        $tablesResult = $connection->select("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");

        foreach ($tablesResult as $tableRow) {
            $rowValues = array_values((array) $tableRow);
            $table = $rowValues[0] ?? null;

            if (!$table) {
                continue;
            }

            $escapedTable = str_replace('`', '``', (string) $table);

            $createRows = $connection->select('SHOW CREATE TABLE `' . $escapedTable . '`');
            if (empty($createRows)) {
                continue;
            }

            $createValues = array_values((array) $createRows[0]);
            $createStatement = $createValues[1] ?? null;

            if (!$createStatement) {
                continue;
            }

            $dump[] = '-- Structure for table `' . $escapedTable . '`';
            $dump[] = 'DROP TABLE IF EXISTS `' . $escapedTable . '`;';
            $dump[] = $createStatement . ';';
            $dump[] = '';

            $rows = $connection->select('SELECT * FROM `' . $escapedTable . '`');

            if (!empty($rows)) {
                $dump[] = '-- Data for table `' . $escapedTable . '`';

                foreach ($rows as $record) {
                    $recordArray = (array) $record;
                    $columns = array_map(function ($column) {
                        return '`' . str_replace('`', '``', (string) $column) . '`';
                    }, array_keys($recordArray));

                    $values = array_map(function ($value) use ($pdo) {
                        return $this->toSqlValue($pdo, $value);
                    }, array_values($recordArray));

                    $dump[] = 'INSERT INTO `' . $escapedTable . '` ('
                        . implode(', ', $columns)
                        . ') VALUES ('
                        . implode(', ', $values)
                        . ');';
                }

                $dump[] = '';
            }
        }

        $dump[] = 'SET FOREIGN_KEY_CHECKS=1;';

        return implode(PHP_EOL, $dump) . PHP_EOL;
    }

    /**
     * Convert a PHP value into a SQL-safe literal.
     */
    private function toSqlValue(\PDO $pdo, $value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        return $pdo->quote((string) $value);
    }

    /**
     * Find mysqldump binary path.
     */
    private function findMysqldump(): string
    {
        // Absolute paths first
        $paths = [
            'C:\\xampp\\mysql\\bin\\mysqldump.exe',
            'C:\\xampp\\mysql\\bin\\mysqldump',
            '/usr/bin/mysqldump',
            '/usr/local/bin/mysqldump',
            '/usr/bin/mariadb-dump',
            '/usr/local/bin/mariadb-dump',
        ];

        foreach ($paths as $path) {
            if (is_file($path)) {
                return $path;
            }
        }

        // Fallback to command names available in PATH
        foreach (['mysqldump', 'mariadb-dump'] as $command) {
            if ($this->isCommandAvailable($command)) {
                return $command;
            }
        }

        throw new \RuntimeException(
            'No database dump binary found. Install mysqldump or mariadb-dump in the runtime image.'
        );
    }

    /**
     * Detect whether a command is available in PATH.
     */
    private function isCommandAvailable(string $command): bool
    {
        $lookup = DIRECTORY_SEPARATOR === '\\'
            ? ['where', $command]
            : ['which', $command];

        $process = new Process($lookup);
        $process->run();

        return $process->isSuccessful() && trim($process->getOutput()) !== '';
    }

    /**
     * Build a useful process error message for UI display.
     */
    private function formatProcessError(Process $process, string $fallback): string
    {
        $stderr = trim($process->getErrorOutput());
        if ($stderr !== '') {
            return $stderr;
        }

        $stdout = trim($process->getOutput());
        if ($stdout !== '') {
            return $stdout;
        }

        $exitCode = $process->getExitCode();
        if ($exitCode !== null) {
            return $fallback . ' (exit code ' . $exitCode . ')';
        }

        return $fallback;
    }

    /**
     * Format bytes to human readable.
     */
    private function formatBytes($bytes, $precision = 2): string
    {
        $units = ['B', 'KB', 'MB', 'GB'];
        $bytes = max($bytes, 0);
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
        $pow = min($pow, count($units) - 1);
        $bytes /= (1 << (10 * $pow));
        return round($bytes, $precision) . ' ' . $units[$pow];
    }
}
